// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cxjqbxhhslxqpkfcwqhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4anFieGhoc2x4cXBrZmN3cWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMDQyMjcsImV4cCI6MjA5MTU4MDIyN30.O6UODSJpjjgcffUR8l4FDB5B28Qn1BdfQ3Cf2nprD88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'lwd-auth-token-v1',
    flowType: 'pkce',
    // Gestore lock personalizzato per evitare il crash "Lock was released because another request stole it"
    // Aggiunto il parametro acquireTimeout per rispettare la firma del tipo LockFunc
    lock: async (name: string, _acquireTimeout: number, callback: () => Promise<any>) => {
      try {
        if (typeof navigator !== 'undefined' && navigator.locks) {
          return await navigator.locks.request(name, callback);
        }
        return await callback();
      } catch (e: any) {
        // Se il lock viene rubato o fallisce, eseguiamo comunque il callback per non bloccare l'app
        if (e.message?.includes('stole') || e.name === 'AbortError') {
          console.warn('[Supabase] Auth lock conflict detected, proceeding without lock.');
          return await callback();
        }
        throw e;
      }
    }
  }
});